### PR TITLE
Issue is happening when ghidra reside on another operating system

### PR DESCRIPTION
**Pull request by ManuSecsearch**
In some cases for example when ghidra ran on a mac os x, and the debiugger is running on Windows, full module path is causing errors into ghidra complaining not beeing able to find the module

### CODE REVIEW

**Comment by ManuSecsearch** [comment]
May be better to optimize ?

**Comment by bootleg** [comment]
Hi, 

thank you to you both for the report and pull request. Based on you description of the issue and the fix proposed by talosmrt, this issue looks like the one I fixed in the IDA plugin (sorry for falling a second time for this)
https://github.com/bootleg/ret-sync/blob/master/ext_ida/retsync/dispatcher.py#L338

I'll just check if there something to do with the Java nio Path API directly.

**Comment by bootleg** [comment]
Hi ManuSecsearch and talosmrt, 

please see commit https://github.com/bootleg/ret-sync/commit/6cb187e52b7285652752971205df4f5c7ae34f63

Thank you for reporting and ideas. I've adapted the fix in a consistent way with the IDA plugin (fixing paths based on remote debugger flavour).

Keeping the request open for a few days; will close it if no issue in the meantime.

Best regards,

**Comment by ManuSecsearch** [comment]
Looks ok now for me with your changes thanks

**Comment by bootleg** [comment]
Great, closing the issue. Will reopen if necessary. Tank you again to you both.

**Pull request closed without merging**
