### PR TITLE
Improve gdb/Ghidra sync

### PR DESCRIPTION
**Pull request by lxp**
This pull requests improves the gdb and Ghidra extensions.

### CODE REVIEW

**Comment by lxp** [comment]
Hi bootleg,
The general reasoning behind the feature is the following: The Ghidra extension needs to know the full module map, so that you can set breakpoints in all modules regardless of the active module in gdb. Otherwise, it is simply not possible to set breakpoints in inactive modules or the address calculation is wrong (e.g. after program start libc _start is active and you want to set a breakpoint on main).

Of course, a separate command might be more appropriate. It was just most convenient to implement it like this.

**Comment by bootleg** [comment]
Yes, my bad with the remark on the overhead.

I'll test it this week I hope. I'd like to make sure not to break the other debuggers extensions.For example, right now, I don't remember why I added this check.

```
if (imageBaseRemote == null) {
    imageBaseRemote = imageBaseLocal.getNewAddress(base);
}
```


 So far I tried to keep the plugins as stateless as possible (as debuggers could crash/vm reboot, etc.) However with gdb the info is easily accessible indeed.

**Comment by bootleg** [comment]
I didn't had much time yet to test. So far, it seems ok to me the only concern would be to silent the output of modules map. I've tried to make the default behavior of ret-sync less verbose (especially true for IDA as people sometimes use plenty of plugins concurently, too much verbosity can be annoying).

As for the extractr:

```
if (imageBaseRemote == null) {
    imageBaseRemote = imageBaseLocal.getNewAddress(base);
}
```

The IDA plugin implementation also updates the imageBaseRemote whenever a new one is recieved so it seems it is ok.

**Comment by bootleg** [comment]
Just merged. I've added a flag to reduce verbosity. Thank you a lot.

**Pull request merged**
